version: "3"

services:

  phpdev:
    image: tbfisher/drupal-php:7.2-dev
    environment:
      PHP_MEMORY_LIMIT: 64M
    volumes:
      - "./test/html:/var/www/html:cached"

  webdev:
    build: ./dev
    ports:
      - '8080:80'
    environment:
      WEB_DOCROOT: /var/www/html
      WEB_PHPFPM: "phpdev:9000"
    volumes:
      - "./test/html:/var/www/html:cached"

